### PR TITLE
[1.16] Make blocks rotatable for structures

### PR DESCRIPTION
**Pull request by Seniorendi**
For further explanation, see #1082 
Every block should now be rotatable for structures. If you see that I missed one, just tell me (:
I also updated forge so that it supports newer versions of java

I'll open a PR for 1.18 in the next days

### CODE REVIEW

**Comment by Seniorendi** [comment]
image
Left is normal, right is rotated by 270°

**Review by SquidDev — CHANGES_REQUESTED** [review]
Looks good, thank you very much! Just a couple of small nitpicks:

 - We tend to use javax's Nonnull annotation instead of Jetbrain's one. JB's is probably better to use nowadays, but I do want to keep things consistent.
 - Can you remove the `p` prefix from parameters? I think Parchment or ForgeGradle adds them in :/.

I assume these rotations only apply around the Y axis - we don't need to worry about a computer trying to face UP/DOWN?

Don't worry about 1.18 (unless it has changed massively!), as I can do that when merging things across.

**Comment by Seniorendi** [comment]
> I assume these rotations only apply around the Y axis - we don't need to worry about a computer trying to face UP/DOWN?

Computers shouldn't be able to rotate UP/DOWN
So I just *hope* this will never happen :P

> * We tend to use javax's Nonnull annotation instead of Jetbrain's one. JB's is probably better to use nowadays, but I do want to keep things consistent.
> * Can you remove the `p` prefix from parameters? I think Parchment or ForgeGradle adds them in :/.

Done (:

> Don't worry about 1.18 (unless it has changed massively!), as I can do that when merging things across.

Kay!
Nothing changed in between 1.16 to 1.18

**Review by SquidDev — APPROVED** [review]

**Comment by SquidDev** [comment]
Thank you very much!

**Pull request merged**
