### PR TITLE
Reduce latency of speakers with direct playback

### PR DESCRIPTION
**Pull request by MCJack123**
This PR replaces the client side of audio playback with direct OpenAL calls, allowing the use of smaller buffers to reduce latency. It also reduces the size of the buffer on the server so that data is sent quicker.

This is pretty experimental, and there's likely some incompatibility/bad practices that I'm overlooking, but from my testing it appears to work very well. There may be some issues with distance attenuation, as it uses its own constants to calculate that, but otherwise all of the positional stuff works fine. This also makes `playAudio` and `playSound` separate, which may not be desirable - this can be fixed with a few simple `if` checks.

### CODE REVIEW

**Comment by SquidDev** [comment]
Could you share the program you're using to test this? At first blush this looks identical to what MC is doing internally (aside from the change to `CLIENT_BUFFER`).

**Comment by MCJack123** [comment]
The program is available [on GitHub](https://github.com/MCJack123/tracc/blob/playAudio/tracc.lua), and the module files I'm using are available here: http://gsf.joshw.info/t/The%20Game%20of%20Life,%20Yahtzee,%20Payday%20(conv)%20(2005-11-07)(Black%20Lantern%20Studios)(Destination%20Software%20Inc.)[GBA].7z

**Comment by SquidDev** [comment]
I just tried this out on my machine, and it sounds incredibly stuttery. Even the `speaker play` program will cut out and then only play occasional starts of audio.

**Comment by znepb** [comment]
A couple of issues I've noticed - it seems the audio isn't categorized under any audio volume slider, nor does it respect distancing (it only stops playing when the chunks are unloaded). Plus, as SquidDev mentions, the audio becomes choppy even if the server is running at 20 TPS.

**Comment by Toad-Dev** [comment]
I had stutter in my testing too. Stutter happens on a coin flip the first time a speaker peripheral is used after freshly loading the world, but always occurs when reusing a speaker peripheral. The reuse issue feels like something wrong with the AL buffer code as it just never recovers and gets increasingly worse with each new stream until the world is reloaded.

I think the change to `CLIENT_BUFFER` is a bit optimistic in general. A 20ms window, when minecraft is ticking the peripheral (ideally) every 50ms, means it's possible for a speaker to pass on sending pending audio one tick, and then be a few ms late on sending that audio the next tick.

**Comment by SquidDev** [comment]
@MCJack123 The above commit hopefully alleviates some of your concerns raised here and #982. We're never going to be able to reduce the latency to a single tick, as that's just not sensible on an SMP server, but I think the current values are Good Enough :tm:.

**Comment by MCJack123** [comment]
It appears the second commit was causing the stuttering. I've reverted it to fix the issue.

> I think the change to `CLIENT_BUFFER` is a bit optimistic in general. A 20ms window, when minecraft is ticking the peripheral (ideally) every 50ms, means it's possible for a speaker to pass on sending pending audio one tick, and then be a few ms late on sending that audio the next tick.

I agree; the value I set it to was mostly just for testing. I've bumped it up to 0.1s, which is lower than Squid changed it to, but it should theoretically be able to handle as low as 10 tps without issues (?).

> @MCJack123 The above commit hopefully alleviates some of your concerns raised here and #982. We're never going to be able to reduce the latency to a single tick, as that's just not sensible on an SMP server, but I think the current values are Good Enough:tm:.

I tried it out, and it is working much better. With the changes, my tracker's now only about 4 rows behind the video. One thing that would be nice is to have `speaker_audio_empty` be sent a bit more regularly at the beginning, as it's sent immediately when starting to play audio and the buffers aren't full yet, but that's probably a bit more work than is necessary.

**Comment by SquidDev** [comment]
I'm going to close this for now, as things are at a state I'm happy with. There's definitely room to change how the internals work once 1.100 is released.

**Pull request closed without merging**
