### PR TITLE
Allow peripherals to have multiple types

### PR DESCRIPTION
**Pull request by SquidDev**
A screenshot of a ComputerCraft turtle showing the output of the "peripherals" program. It lists two peripherals - a furnace and a chest - each with their own distinct type as well as an additional "inventory" type

Peripherals can now have multiple types:
 - A single primary type. This is the same as the current idea of a type - some identifier which (mostly) uniquely identifies this kind of peripheral. For instance, "speaker" or "minecraft:chest".
 - 0 or more "additional" types. These are more like traits, and describe what other behaviour the peripheral has - is it an inventory? Does it supply additional peripherals like a wired modem)?.

This is mostly intended for the generic peripheral system, but it might
prove useful elsewhere too - we'll have to see!

 - `peripheral.getType` (and `modem.getTypeRemote`) now returns 1 or more values, rather than exactly one.
 - Add a new `peripheral.hasType` (and `modem.hasTypeRemote`) function which determines if a peripheral has the given type (primary or additional).
 - Change peripheral.find and all internal peripheral methods to use `peripheral.hasType` instead.
 - Update the peripherals program to show all types.

This effectively allows you to do things like `peripheral.find("inventory")` to find all inventories.

---

### Still left to do
I put this together in an hour while waiting for food to cook, it's very WIP.

 - [x] Documentation. I think this is a good opportunity to flesh out the peripheral API docs in general - I suspect there's more detail we could go into in the introductory paragraphs.
 - [x] Tests.
 - [x] Add additional types for fluids and energy methods too.
 - [ ] Add an additional type for "peripheral providers" (see #902) and swap over to this.

---

API is undecided on, and still not sure if this is a good/useful feature. Would appreciate any feedback!

Some outstanding questions:
 - Is `peripheral.hasType` or `peripheral.isType` better?
 - Do we need to have a separate `getTypes` function instead of changing the signature of `getType`?

### CODE REVIEW

**Comment by Lupus590** [comment]
So with this new system, a turtle would turn up as a `computer` type and an `inventory` type? That will make network-based inventories with turtles so much easier.

**Comment by SquidDev** [comment]
> So with this new system, a turtle would turn up as a computer type and an inventory type? 

Well, could. This PR doesn't actually make that specific change.

**Comment by hugeblank** [comment]
If I'm reading this correctly the changes to `getType` and `hasType` would break CC programs that use those methods. Maybe a couple new methods:`getTrait(s)` and `hasTrait(s)` to provide and test the traits of a peripheral could be better?

**Comment by SquidDev** [comment]
> If I'm reading this correctly the changes to `getType` and `hasType` would break CC programs that use those methods.

Well, `hasType` is new, so shouldn't break anything.

`getTypes` might break when used in a varargs context (e.g. `("hello"):gsub("hello", peripheral.getType())` will error if `getType` returns multiple values) - I'm not sure if this is a concern in practice. If we think it is, possibly could use `getTypes`? - I think I want to avoid using "trait" in user-facing documentation, as it's a whole 'nother term to introduce.

**Comment by SquidDev** [comment]
Checking my local notes I had on this, and I originally suggested `peripheral.isType` instead of `peripheral.hasType`. What do people think is a better name?

**Comment by Lupus590** [comment]
`has` implies that a peripheral can have multiple, whereas `is` doesn't, I'd go with `has`

**Comment by SquidDev** [comment]
I need to write some tests for this, but otherwise I think this is ready. Will leave it to sit for a few days in case anyone else has any comments, and then will merge and push an update on the 30th (assuming all goes to plan).

**Pull request merged**
